## Generated at 16:48 on December 09 2025 by marialei
# git version: not on git (not on git)
# To re-generate, run python /home/marialei/mcmule-environment/bin/pymule create \
#      --seeds 77690 13360 46530 90833 28156 51921 44305 76996 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir mp2mp_testNLO \
#      --mcmule mcmule \
#      --stat 0,10,5,100,5,2 \
#      --stat F,10,5,100,5,2 \
#      --stat R,50,5,500,5,2 \
#      --stat A,10,5,100,5,2
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/home/marialei/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 10, itmx_pre = 5, ncall = 100, itmx = 5 }
mp2mpF = { ncall_pre = 10, itmx_pre = 5, ncall = 100, itmx = 5 }
mp2mpR = { ncall_pre = 50, itmx_pre = 5, ncall = 500, itmx = 5 }
mp2mpA = { ncall_pre = 10, itmx_pre = 5, ncall = 100, itmx = 5 }
