## Generated at 14:54 on May 07 2026 by marialei
# git version: b'main' (b'1895373')
# To re-generate, run python /home/marialei/mcmule-environment/bin/pymule create \
#      --seeds 68623 91843 35852 68766 92630 84868 19955 13147 34882 96319 75308 77963 61156 20440 85394 70022 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir mp2mp_NLO_07_05 \
#      --mcmule mcmule \
#      --stat 0,1000,10,10000,10,4 \
#      --stat F,1000,10,10000,10,4 \
#      --stat R,2000,10,50000,10,4 \
#      --stat A,1000,10,10000,10,4
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/home/marialei/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpF = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpR = { ncall_pre = 2000, itmx_pre = 10, ncall = 50000, itmx = 10 }
mp2mpA = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
