## Generated at 13:21 on May 28 2026 by ge93juy
# git version: b'main' (b'757719e')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 46781 72838 67576 77010 68335 65756 53283 45045 28151 55182 43811 33019 34424 45104 18332 51835 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir 28_05_200MeV_relQ2_smathmu \
#      --mcmule mcmule \
#      --stat 0,20000,10,800000,10,4 \
#      --stat F,20000,10,800000,10,4 \
#      --stat R,20000,10,800000,10,4 \
#      --stat A,20000,10,800000,10,4
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 20000, itmx_pre = 10, ncall = 800000, itmx = 10 }
mp2mpF = { ncall_pre = 20000, itmx_pre = 10, ncall = 800000, itmx = 10 }
mp2mpR = { ncall_pre = 20000, itmx_pre = 10, ncall = 800000, itmx = 10 }
mp2mpA = { ncall_pre = 20000, itmx_pre = 10, ncall = 800000, itmx = 10 }
