## Generated at 17:48 on June 09 2026 by ge93juy
# git version: b'main' (b'34dc4a9')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 86708 82149 67856 18122 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir 09_06_Q2big_thmunorm_200MeV_nobands \
#      --mcmule mcmule \
#      --stat 0,2000,15,10000,10,1 \
#      --stat F,2000,15,10000,10,1 \
#      --stat R,5000,15,30000,10,1 \
#      --stat A,2000,15,10000,10,1
[McMule]

# specify the program to run relative to `pwd`
#mcmule = "mcmule"
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 2000, itmx_pre = 15, ncall = 10000, itmx = 10 }
mp2mpF = { ncall_pre = 2000, itmx_pre = 15, ncall = 10000, itmx = 10 }
mp2mpR = { ncall_pre = 5000, itmx_pre = 15, ncall = 30000, itmx = 10 }
mp2mpA = { ncall_pre = 2000, itmx_pre = 15, ncall = 10000, itmx = 10 }
