# ANALYZE TGEANT INPUT


# ============================================================
# Input
# ============================================================

inputfile="/nfs/momos/user/mleibelt/TGEANT_runs/output/LO_scaled_26_08_run000.tgeant.gz"


# ============================================================
# Histogram output
# ============================================================

histogramfile="/nfs/momos/user/mleibelt/TGEANT_runs/output/LO_scaled_26_08_run000.root"


# ============================================================
# Figure output folder
# ============================================================

figurebase="/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/AMBER_RadCor/Figures/AMBER_eventgen"
figurefoldername="26_08_LO"

