# LHE TO ROOT - INPUT

# code folder
codefolder="/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/AMBER_RadCor/Code"

# folders
folder="/nfs/momos/user/mleibelt/05_08_evtgen_25_08/out"
outfolder="/nfs/momos/user/mleibelt/05_08_evtgen_25_08/out"

# inputfiles 
inputfile_LO="05_08_evtgen_25_08_LO_tgteffe-2.root"
inputfile_NLO="05_08_evtgen_25_08_NLO_tgteffe-2.root"

# CS
CSfile="/nfs/momos/user/mleibelt/05_08_evtgen_25_08/14_08_05_08_evtgen_cross_sections.txt"

# index
addindex="26_08"

