## Generated at 20:30 on May 07 2026 by ge93juy
# git version: b'main' (b'6adef3c')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 95100 12768 94723 93467 20250 87881 86014 55405 50435 49900 54122 78930 68601 85605 20745 14372 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir mp2mp_NLO_07_05_Themis \
#      --mcmule mcmule \
#      --stat 0,1000,10,10000,10,4 \
#      --stat F,1000,10,10000,10,4 \
#      --stat R,2000,10,50000,10,4 \
#      --stat A,1000,10,10000,10,4
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpF = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpR = { ncall_pre = 2000, itmx_pre = 10, ncall = 50000, itmx = 10 }
mp2mpA = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
