## Generated at 16:34 on July 02 2026 by ge93juy
# git version: b'main' (b'fd1c687')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 54415 62659 15986 20397 54983 51930 75233 39265 40601 16196 46904 30121 46708 77470 60003 95969 52423 46196 37627 91475 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir 02_07_200MeV_Q2big_xi01_onlyR_Mehran_noEmucut_correct \
#      --mcmule mcmule \
#      --stat 0,10000,15,80000,20,5 \
#      --stat F,10000,15,80000,20,5 \
#      --stat R,10000,15,80000,20,5 \
#      --stat A,10000,15,80000,20,5
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/mcmule-release/mcmule"
# mcmule = "mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
mp2mpF = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
mp2mpR = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
mp2mpA = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
