# LHE TO ROOT - INPUT

# code folder
codefolder="/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/AMBER_RadCor/Code"

# folders
folder="/nfs/momos/user/mleibelt/05_08_evtgen_25_08/out"

# LO
inputfile_LO="gen-N-0-10-29334.lhe"
outputfile_LO="05_08_evtgen_25_08_LO_tgteffe-2.root"

# NLO
inputfile_NLO="gen-CU-1-01-67347.lhe"
outputfile_NLO="05_08_evtgen_NLO_25_08_tgteffe-2.root"
