# TGEANT INPUT

# TGEANT runs folder
TGEANTrunsfolder="/nfs/momos/user/mleibelt/TGEANT_runs"

# Number of events
Eventnumber="173861"

# LO Input ROOT file
inputfile="/nfs/momos/user/mleibelt/05_08_evtgen_25_08/out/LO_scaled_26_08.root"

# NLO ROOT file alternative
#inputfile="/nfs/momos/user/mleibelt/05_08_evtgen_25_08/out/NLO_scaled_26_08.root"

# Output
outputfolder="/nfs/momos/user/mleibelt/TGEANT_runs/output"
outputname="LO_scaled_173861evts"
