# ============================================================
# MCMULE EVENT GENERATOR INPUT
# ============================================================

basefolder="/nfs/momos/user/mleibelt"
anafolder="evtgen_31_08"


# ============================================================
# gen settings
# ============================================================

nenter_LO=500
itmx_LO=12

nenter_NLO=500
itmx_NLO=12

tgteff=1e-1
nsub=30
dmax=1.

# ============================================================
# McMule files
# ============================================================

# xi = 0.1

mcmule0_xi01="mp2mp0_mu-p_S0000077682X1.00000D1.00000_ITMX020x080.0M.mcmule"

mcmuleNLO0_xi01="mp2mpNLO0_mu-p_S0000075957X0.10000D0.10000_ITMX020x080.0M.mcmule"

mcmuleR_xi01="mp2mpR_mu-p_S0000023375X0.10000D0.10000_ITMX020x080.0M.mcmule"


# xi = 1.0

mcmule0_xi10="mp2mp0_mu-p_S0000077682X1.00000D1.00000_ITMX020x080.0M.mcmule"

mcmuleNLO0_xi10="mp2mpNLO0_blabla.mcmule"

mcmuleR_xi10="mp2mpR_blabla.mcmule"


# ============================================================
# rungen settings
# ============================================================

xi="01"

seed_LO=29337
seed_NLO=75236
seed_NLO_CU=67387



