# Compare MCMULE & AMBER TGEANT - INPUT

# code folder
codefolder="/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/AMBER_RadCor/Code"


# inputfiles 
inputfile_mcmule=""
inputfile_amber=""

# Folder
outfolder="/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/AMBER_RadCor/Figures/compare_mcmule_amber"

