# ==========================================
# CROSS SECTION INPUT
# ==========================================

# Project directory
HOMEDIR="/nfs/momos/user/mleibelt"

# Code directory
CODEDIR="/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/AMBER_RadCor/Code"
# Folder wher cs will be saved
OUTFOLDER="31_08_evtgen"

# Name used for output files
SAVENAME="01_09"
