# =========================
# Paths
# =========================

HOMEDIR="/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/AMBER_RadCor"

OUTDIR="${HOMEDIR}/Figures"
OUTDIR_VALS="${HOMEDIR}/Vals"


# =========================
# Input
# =========================

RUN="09_07_xi01_Mehran"


# =========================
# Output
# =========================

SAVENAME="14_07"

NBINS=500
