## Generated at 17:33 on May 20 2026 by ge93juy
# git version: b'main' (b'1ba4b60')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 43985 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir test_20_05 \
#      --mcmule mcmule \
#      --stat R,100,10,1000,10,1
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mpR = { ncall_pre = 100, itmx_pre = 10, ncall = 1000, itmx = 10 }
