## Generated at 08:15 on May 20 2026 by ge93juy
# git version: b'main' (b'6d34ffb')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 94798 61501 15496 96042 41411 58240 84996 25012 80456 85115 54288 87085 10030 80361 58343 85861 24882 95262 15433 86669 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir 20_05_Eph500MeV_SMALL \
#      --mcmule mcmule \
#      --stat 0,1000,10,10000,10,5 \
#      --stat F,1000,10,10000,10,5 \
#      --stat R,2000,10,50000,10,5 \
#      --stat A,1000,10,10000,10,5
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpF = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpR = { ncall_pre = 2000, itmx_pre = 10, ncall = 50000, itmx = 10 }
mp2mpA = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
