## Generated at 22:59 on April 28 2026 by marialei
# git version: b'main' (b'b842ee5')
# To re-generate, run python /home/marialei/mcmule-environment/bin/pymule create \
#      --seeds 46939 92425 93060 90063 99500 10174 33593 85849 30228 74356 81636 74102 33358 31257 88032 19853 21576 60882 69374 59202 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir mp2mp_NLO_28_04 \
#      --mcmule mcmule \
#      --stat 0,1000,10,20000,10,5 \
#      --stat F,1000,10,20000,10,5 \
#      --stat R,2000,10,70000,10,5 \
#      --stat A,1000,10,20000,10,5
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 1000, itmx_pre = 10, ncall = 20000, itmx = 10 }
mp2mpF = { ncall_pre = 1000, itmx_pre = 10, ncall = 20000, itmx = 10 }
mp2mpR = { ncall_pre = 2000, itmx_pre = 10, ncall = 70000, itmx = 10 }
mp2mpA = { ncall_pre = 1000, itmx_pre = 10, ncall = 20000, itmx = 10 }
