## Generated at 03:43 on May 13 2026 by ge93juy
# git version: b'main' (b'b7d6801')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 57719 55923 23609 46662 39210 76579 40361 80275 96440 77982 15613 88889 65947 33483 57922 53176 74483 85589 67187 47155 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir mp2mp_NLO_13_05_TH500MeV_SMALL \
#      --mcmule mcmule \
#      --stat 0,1000,10,10000,10,5 \
#      --stat F,1000,10,10000,10,5 \
#      --stat R,2000,10,50000,10,5 \
#      --stat A,1000,10,10000,10,5
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpF = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpR = { ncall_pre = 2000, itmx_pre = 10, ncall = 50000, itmx = 10 }
mp2mpA = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
