## Generated at 17:59 on June 09 2026 by ge93juy
# git version: b'main' (b'34dc4a9')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 84365 22587 43679 64922 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir 09_06_Q2big_thmunorm_200MeV_nobands_10xmorepoints \
#      --mcmule mcmule \
#      --stat 0,20000,15,100000,10,1 \
#      --stat F,20000,15,100000,10,1 \
#      --stat R,50000,15,300000,10,1 \
#      --stat A,20000,15,100000,10,1
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
#mcmule = "mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 20000, itmx_pre = 15, ncall = 100000, itmx = 10 }
mp2mpF = { ncall_pre = 20000, itmx_pre = 15, ncall = 100000, itmx = 10 }
mp2mpR = { ncall_pre = 50000, itmx_pre = 15, ncall = 300000, itmx = 10 }
mp2mpA = { ncall_pre = 20000, itmx_pre = 15, ncall = 100000, itmx = 10 }
