## Generated at 14:14 on July 01 2026 by ge93juy
# git version: b'main' (b'e97b1f3')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 27571 83036 74410 41486 61680 80040 22257 47047 83178 84742 25845 46225 67233 34050 39944 91415 91493 66796 79192 15574 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir 01_07_200MeV_Q2big_xi01 \
#      --mcmule mcmule \
#      --stat 0,10000,15,80000,20,5 \
#      --stat F,10000,15,80000,20,5 \
#      --stat R,10000,15,80000,20,5 \
#      --stat A,10000,15,80000,20,5
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/freenas/tuph/e18/project/prm/mleibelt/AMBER_Repo/mcmule-release/mcmule"
#mcmule = "mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
mp2mpF = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
mp2mpR = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
mp2mpA = { ncall_pre = 10000, itmx_pre = 15, ncall = 80000, itmx = 20 }
