## Generated at 14:53 on March 24 2026 by ge93juy
# git version: b'main' (b'74d865c')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 12234 38317 12587 72498 91056 46202 87350 39433 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir mp2mp_NLO_24_03 \
#      --mcmule mcmule \
#      --stat 0,100,10,1000,10,2 \
#      --stat F,100,10,1000,10,2 \
#      --stat R,1000,10,10000,10,2 \
#      --stat A,100,10,1000,10,2
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mp0 = { ncall_pre = 100, itmx_pre = 10, ncall = 1000, itmx = 10 }
mp2mpF = { ncall_pre = 100, itmx_pre = 10, ncall = 1000, itmx = 10 }
mp2mpR = { ncall_pre = 1000, itmx_pre = 10, ncall = 10000, itmx = 10 }
mp2mpA = { ncall_pre = 100, itmx_pre = 10, ncall = 1000, itmx = 10 }
