## Generated at 12:25 on June 09 2026 by ge93juy
# git version: b'main' (b'd15e442')
# To re-generate, run python /nfs/mnemosyne/user/ge93juy/private/.local/bin/pymule create \
#      --seeds 72490 \
#      -xi 0.1 \
#      --genprocess mp2mp \
#      --output-dir 09_06_thmu4xbigger_noEphcut2 \
#      --mcmule mcmule \
#      --stat R,5000,10,30000,10,1
[McMule]

# specify the program to run relative to `pwd`
mcmule = "/nfs/mnemosyne/user/ge93juy/private/mcmule-release/mcmule"
#mcmule = "mcmule"
# Specify the variables nenter_ad, itmx_ad, nenter and itmx
# for each piece you want to run.

[McMule.statistics.vegas]
mp2mpR = { ncall_pre = 5000, itmx_pre = 10, ncall = 30000, itmx = 10 }
